### ISSUE TITLE
안녕하세요! 

### ISSUE THREAD

**Issue by Shin-jun** [dualcoder-pe/android_tflite#1]
안녕하세요 텐서플로 라이트를 활용한 안드로이드 딥러닝 책에 대해서 공부하고 있는 독자입니다.
텐서플로우 허브에서 tf파일을 활용해서 커스텀하는 방법도 똑같나요? 같은 방법으로 할경우
java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (input) with 110592 bytes from a Java Buffer with 442368 bytes.
오류가 나타납니다. 감사합니다

**Comment by Shin-jun** [comment]
dataType이 안맞아서 그러는것같은데 UINT8 데이터타입으로 포멧된 tflite 적용 방법이 궁금합니다.

**Comment by dualcoder-pe** [comment]
안녕하세요. 확인이 늦어 죄송합니다.
말씀하신 내용은 p.341 ~ p.342에 제시된 코드 9-15를 참조하시면 될 것 같습니다.
해당 코드에서 input_details와 output_details의 'dtype'에 따라 분기되는 코드들을 중점적으로 보시기 바랍니다.
감사합니다.
