### ISSUE TITLE
안녕하세요. 책 코드 동작에 대해 여쭙고 싶어 씁니다.

### ISSUE THREAD

**Issue by RoosterJang** [dualcoder-pe/android_tflite#2]
안녕하세요. 책을 열심히 따라 공부하고 있습니다. ^^

그런데 128쪽의 AndroidDraw를 로딩하는 과정에 오류가 생기고 build.gradle의 형태가 현재 안드로이드 스튜디오의 그것과 차이가 있습니다.
3개월만에 많은 변화가 있었나 봅니다. 확인 부탁드립니다.

감사합니다.
참고로 안드로이드 스튜디오 버전은 아크틱폭스 2021년 10월 1일 빌트된 버전에서  JAVA로 연습 중입니다.

**Comment by postBG** [comment]
안녕하세요. 전 책 저자나 그런 사람은 아니고요...

"maven {url 'https://jitpack.io'}"을 allprojects/repositories 밑에 넣으면 계속 warning이나 error가 뜨거나, AndroidDraw을 찾지 못하더군요.
에러메시지는 설정에 따라 조금씩 다를텐데, 다음과 비슷할겁니다.
"Build was configured to prefer settings repositories over project repositories but repository 'maven' was added by build file 'build.gradle'"
에러메시지를 읽어보니까 settings.gradle의 repositories를 더 선호한다는 것 같습니다.
그래서 전 settings.gradle의 repositories에 maven {url ...} 문구를 넣고 실행했더니 해결됐습니다.
아직 문제가 해결되지 않으셨다면 한번 시도해보세요.

**Comment by RoosterJang** [comment]
답변 감사합니다. 아마도 책의 오류인 것 같습니다. ^^ 
build.gradle이 아니고 settings.gradle 인 것 같네요. 삽화의 내용과 레포지터리 내용이 동일하네요. ^^
많은 도움이 되었습니다. ^^

> 안녕하세요. 전 책 저자나 그런 사람은 아니고요...
> 
> "maven {url '[https://jitpack.io'}"을](https://jitpack.io'%7D%22%EC%9D%84) allprojects/repositories 밑에 넣으면 계속 warning이나 error가 뜨거나, AndroidDraw을 찾지 못하더군요. 에러메시지는 설정에 따라 조금씩 다를텐데, 다음과 비슷할겁니다. "Build was configured to prefer settings repositories over project repositories but repository 'maven' was added by build file 'build.gradle'" 에러메시지를 읽어보니까 settings.gradle의 repositories를 더 선호한다는 것 같습니다. 그래서 전 settings.gradle의 repositories에 maven {url ...} 문구를 넣고 실행했더니 해결됐습니다. 아직 문제가 해결되지 않으셨다면 한번 시도해보세요.

**Comment by dualcoder-pe** [comment]
안녕하세요.
제보해주신 분, 답변주신 분 모두 감사드립니다.

책을 출간한 뒤 짧은 시간 동안 기본 코드가 변경되고 jcenter 레포지토리가 서비스 종료하는 등
이례적으로 많은 변화가 있었네요.

확인해보니 Arctic Fox에서부터 기본으로 생성되는 코드가 변경되었습니다.
Repository 관련 설정이 settings.gradle파일로 이동되었어요.
아마 깃헙에서 기존 코드 받아서 작업하신 분들은 이상이 없겠지만,
Arctic Fox에서 새로 프로젝트 만들어서 따라하셨다면 문제가 발생하셨을거에요.

혹시 아직 해결 안되신분들은 maven관련 설정을
Project의 build.gradle이 아니라, 
settings.gradle에 있는 dependencyResolutionManagement 블록 내 repositories 안에 하시면 되겠습니다.

조만간 코드 업데이트 하도록 하겠습니다 :)
