### ISSUE TITLE
안녕하세요. 텐서플로 라이트를 활용한 안드로이드 딥러닝 따라 해 보고 있는데요~

### ISSUE THREAD

**Issue by icon001** [dualcoder-pe/android_tflite#3]
5장에서 
dependencies -> implementation 'com.github.divyanshub024:AndroidDraw:v0.1'
repositories -> maven { url 'https://jitpack.io' }
이것을 추가 하고
activity_draw.xml 파일에 
<com.divyanshu.draw.widget.DrawView 을 추가하는 데 에러가 나오는데 혹시 다른 부분을 셋팅 해 주어야 하는 부분이 있는지 궁금합니다.

**Comment by dualcoder-pe** [comment]
안녕하세요. 혹시 build.gradle 파일을 수정하신 뒤에 Sync Project with Geadle Files를 하셨나요?
p.129의 [그림 3-26]을 참조하시면 됩니다.
감사합니다.

**Comment by icon001** [comment]
네 Sync Project with Geadle Files 까지 작업 했거든요..ㅠ.ㅠ
깃허브에 올라온 소스코드를 다운받아서 오픈했을때는 에러가 없는데~
새로 프로젝트를 생성해서 다음과 같이 작업 한 경우는 그렇게 에러가 뜨는데요..ㅠ.ㅠ

**Comment by icon001** [comment]
> 안녕하세요. 혹시 build.gradle 파일을 수정하신 뒤에 Sync Project with Geadle Files를 하셨나요? p.129의 [그림 3-26]을 참조하시면 됩니다. 감사합니다.

네 Sync Project with Geadle Files 까지 작업 했거든요..ㅠ.ㅠ
깃허브에 올라온 소스코드를 다운받아서 오픈했을때는 에러가 없는데~
새로 프로젝트를 생성해서 다음과 같이 작업 한 경우는 그렇게 에러가 뜨는데요..ㅠ.ㅠ

**Comment by icon001** [comment]
> 안녕하세요. 혹시 build.gradle 파일을 수정하신 뒤에 Sync Project with Geadle Files를 하셨나요? p.129의 [그림 3-26]을 참조하시면 됩니다. 감사합니다.

제가 잘못 했네요...ㅠ.ㅠ
allprojects 에 추가해야 되는데..
buildscript 에 추가를 해서 그랬습니다.

감사합니다.^^

**Comment by yourms** [comment]
안녕하세요.. 4장 dev_tfhub.ipynb 파일에 문제가 있어보여 글남깁니다.
```python
hub_model_transfer.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
 
hub_model_transfer.fit(train_batch, epochs=5)
```

아래 부분에 이미지 표시 및 예측 문자 출력부분을 제가 아래와 같이 수정해 보았습니다.

```python
from PIL import Image
import os
import numpy as np

data_dir = "./images/"
files = os.listdir(data_dir)

images = []
for file in files:
    path = os.path.join(data_dir, file)
    images.append(np.array(Image.open(path)))
    
resized_images = np.array(np.zeros((len(images), 224, 224, 3))) # 0으로 초기화된 array를 만들고 
for i in range(len(images)):
    resized_images[i] = tf.image.resize(images[i], [224, 224]) # resize로 이미지 크기변경 하여 array에 담아.

preprocessed_images = tf.keras.applications.mobilenet_v2.preprocess_input(resized_images) # 입력값 전처리

from matplotlib import pyplot as plt
import numpy as np
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

for i in range(len(images)):
    plt.imshow(images[i])
    plt.show()
    
    print("preprocessed_images[i].shape : ", preprocessed_images[i].shape)
    prediction_scores = hub_model_transfer.predict(np.expand_dims(preprocessed_images[i], axis=0))
    print("prediction_scores : ", prediction_scores)
    
    logi_val = sigmoid(prediction_scores)
    print("logi_val : ", logi_val)
    if (logi_val >= 0.5):
        print('Dog')
    else :
        print('Cat')
```
책에 있는 대로는 실행이 되지않아 수정해 보았습니다.
책이 수정이 될 수 있다면 좋을것 같아 올립니다.
좋은책 써주셔서 감사합니다.
